### DISCUSSION TITLE
dynamic = ["version"] in new pyproject.toml build

### DISCUSSION THREAD

**Discussion by nschloe** [pypa/setuptools#3190] [Q&A] [answered]
I'm testing the brand-new `pyproject.toml` build backend.
```toml
[build-system]
requires = [
  "setuptools @ git+https://github.com/pypa/setuptools",
]
build-backend = "setuptools.build_meta"
```
When using 
```toml
[project]
# ...
dynamic = ["version"]
```
the version is always set to 0.0.0, so I guess setuptools doesn't pick it up from the packages `__version__`. Fair enough, I've never told it so. How can I though?

(So far, I've always used flit which does it automatically.)

**Comment by abravalheri** [comment, marked as answer]
Hi @nschloe thank you very much for trying it out.

To get the version from an attribute you can use:

```toml
[tool.setuptools.dynamic]
version = {attr = "mymodule.__version__"}
```

**Reply by abravalheri** [reply]
There are other couple of ways of using the dynamic value, one of them is via `setuptools-scm/setuptools-svn`, and the other is via

```toml
[tool.setuptools.dynamic]
version = {file = ["VERSION.txt"]}
```

(it should work similarly to the way `setup.cfg` currently works, apart from the different tables and the new `dynamic` field)
