### DISCUSSION TITLE
How to setup home-page in pyproject.toml

### DISCUSSION THREAD

**Discussion by se7enXF** [pypa/setuptools#3318] [Q&A] [answered]
I follow [this guide](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#urls) and code my pyproject.toml  like this: 
```toml
...
[project]
name='[package_name]'
...
urls = {'home-page' = 'xxx.xxx'} 
```

When I install the package and show info of package by using `pip show [package_name]`, there is empty after `Home-page:`.
There is no example in [core-metadata](https://packaging.python.org/en/latest/specifications/core-metadata/#home-page) for setup home-page in pyproject.toml. Am I missing something?
