### DISCUSSION TITLE
Is there a way to use other extras for defining the "all" extra in pyproject.toml?

### DISCUSSION THREAD

**Discussion by maxnoe** [pypa/setuptools#3627] [Q&A] [answered]
In `setup.cfg` (and through code in `setup.py`) it was possible to define extras using other extras, which is particularly useful for providing a `dev` or `all` extra.

E.g. like this:

```
docs = 
    sphinx
    sphinx_rtd_theme
tests = 
    pytest
all = 
	%(tests)s
	%(docs)s
```

Is something similar possible with `pyproject.toml`?

**Comment by abravalheri** [comment]
Hi @maxnoe, the short answer is that currently this is not possible.

TOML does not offer any special syntax for that and the [specs about `pyproject.toml`](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/) also don't make any special provisioning.

*Things/hacks that you can do right now to achieve the expected results:*

- You can use [`dynamic`](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dynamic) for `optional-dependencies` in `pyproject.toml` and keep `setup.cfg` or `setup.py` just for the `extras_require`.
- You can try to "carefully hack" regular `dependencies` by crafting environment markers using `extra` (as specified in [PEP 508](https://peps.python.org/pep-0508/)). You should probably test this one (I think it would work, but I am not 100% sure, it is very likely that you still need to declare the `optional-dependencies` groups even if empty).

**Reply by Joshuaalbert** [reply]
I like this approach the most.

```python
# setup.py
from setuptools import setup

def load_requirements(file_name):
    with open(file_name, "r") as file:
        return [line.strip() for line in file if line.strip() and not line.startswith("#")]

setup(
    install_requires=load_requirements("requirements.txt"),
    extras_require={
        "examples": load_requirements("requirements-examples.txt"),
        "tests": load_requirements("requirements-tests.txt"),
        "all": load_requirements("requirements-tests.txt") + load_requirements("requirements-examples.txt")
    }
)
```

Then inside pyproject.toml

```toml
# pyproject.toml

[project]
# Rest of stuff
dynamic = ["dependencies", "optional-dependencies"]
```

**Comment by maxnoe** [comment, marked as answer]
@abravalheri I think I found a good solution, it seems it is possible (though I am not sure this is specified somewhere or just an accident) to depend on the package itself in `pyproject.toml` like this:

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "test_self_dep"
version = "0.1.0"
dependencies = [
    "requests",
]

[tool.setuptools.packages.find]
where = ["src"]


[project.optional-dependencies]
docs = [
    "sphinx",
]
tests = [
    "pytest",
]
all = [
    "test_self_dep[docs,tests]"
]
```

If that is indeed intentional, might we add this example to the docs?
