### DISCUSSION TITLE
Build step needs to invoke external code generation tool

### DISCUSSION THREAD

**Discussion by infn-ke** [pypa/setuptools#4634] [Q&A]
Can a toml file be used to describe a build step for generating some files? E.g I want to invoke a code generation tool that generates from python files. I tried to use `build_py`, but not sure about the syntax. Something like this;

```toml
[tool.setuptools.commands]
build_py.pre = ./my_code_gen_tool.sh
```
