### DISCUSSION TITLE
How can I specify a dependency as a git repository with branch name in pyproject.toml?

### DISCUSSION THREAD

**Discussion by rinarakaki** [pypa/setuptools#4686] [Q&A] [answered]
You can do this with poetry with this schema:

```toml
[tool.poetry.dependencies]
some-package = { git = "https://github.com/some/repository.git", branch = "next" }
```

I tried this syntax below but it didn't work:

```toml
dependencies = [
  "some-package@git+https://github.com/some/repository.git@next",
  # or
  "some-package@git+https://github.com/some/repository.git#egg=next",
]
```

Can anyone please tell me how to do it correctly?

Sorry, but not sure if I'm posting on a right project (https://github.com/pypa/pip or other project is more appropriete?).
