### DISCUSSION TITLE
Automatic discovery, SWIG wrappers, and pyproject toml

### DISCUSSION THREAD

**Discussion by stephematician** [pypa/setuptools#5028] [Q&A]
## Summary

I want to include a SWIG-generated wrapper module called `cext` (which wraps the _internal_ `_cext` library that SWIG generates for me, too).

When I build the project I see that, although `cext.py` is generated, it is not added to the dist or wheel:

```console
user@host:~/<project_folder>$ python -m build
...
swigging src/foo_module/cext.i to src/foo_module/cext_wrap.c
swig -python -I./src/foo_module/include -o src/foo_module/cext_wrap.c src/foo_module/cext.i
creating build/temp.linux-x86_64-cpython-312/src/foo_module
...
adding 'foo_module/__init__.py'
adding 'foo_module/_cext.cpython-312-x86_64-linux-gnu.so'
adding 'foo_module/cext.i'
adding 'foo_module/include/foo_module/foo_module.h'
adding 'foo_project-0.0.1.dev0.dist-info/METADATA'
adding 'foo_project-0.0.1.dev0.dist-info/WHEEL'
adding 'foo_project-0.0.1.dev0.dist-info/top_level.txt'
adding 'foo_project-0.0.1.dev0.dist-info/RECORD'
...
```

So when I try to import (obviously):

```py
import foo_module.cext
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ModuleNotFoundError: No module named 'foo_module.cext'
import foo_module._cext
# OK - but only internal module, doesn't have Python wrappers
```

What's the simplest (and most future-proof) way to get the desired result that `cext.py` is included?

## Details of MWE

1.  Broadly speaking I'm using [src-layout](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout) for package discovery.
2.  I have an "include" folder that will contain headers to be distributed with the package (similar to how Numpy might share headers).

```
<project_folder>
├── MANIFEST.in
├── pyproject.toml
└── src/
    └── foo_module/
        ├── __init__.py
        ├── cext.i
        └── include/
            └── foo_module/
                └── foo_module.h
```

A `MANIFEST.in` is required to ensure the headers are packaged:

```
recursive-include src/foo_module/include *.h
```

Here's how I think the `pyproject.toml` would look:

```toml
[project]
name = "foo_project"
version = "0.0.1.dev0"

[build-system]
requires = ["setuptools"]

[[tool.setuptools.ext-modules]]
name = "foo_module._cext"
sources = ["src/foo_module/cext.i"]
swig-opts = ["-I./src/foo_module/include"]
include-dirs = ["src/foo_module/include"]

[tool.setuptools.packages.find]
where = ["src"]
```

The contents of `cext.i` are:

```swig
%module cext
%{
#include "foo_module/foo_module.h"
%}

%include "foo_module/foo_module.h"
```

So, basically, I want to wrap all the structures that I declare in `foo_module.h` and a few enums, and so forth. But for a minimal example, can add anything to `foo_module.h` that we like, e.g.

```c
/* foo_module.h */
#define bar 0
```
