### ISSUE TITLE
[BUG] MANIFEST.in fails to conusme "dotted" directories

### ISSUE THREAD

**Issue by brianthelion** [pypa/setuptools#2805]
### setuptools version

setuptools==58.1.0

### Python version

Python 3.8

### OS

Ubuntu 20.10

### Description

Assume the following package structure, where `:` denotes a directory
```yaml
- setup.py
- setup.cfg
- MANIFEST.in
- src:
  - foo:
    - foo1.yaml
    - foo2.yaml
  - bar:
    - bar1.yaml
    - bar2.yaml
  - zha.baz:
    - zhab.yaml
```
Next assume `MANIFEST.in` contains the following:
```
recursive-include src *.*
```
Then run `python setup.py bdist_wheel && unzip -l *.whl`

### Expected behavior

# Expected

The unzip output will show `foo`, `bar`, and `baz.zha`. All yaml files will be present.

# Actual

The unzip output will only shows `foo` and `bar` et al; `baz.zha` and its files are missing.

### How to Reproduce

As above.

### Output

```console
python setup.py bdist_wheel && unzip -l dist/*.whl
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct
