### ISSUE TITLE
[BUG] dynamic readme guesses incorrect content-type

### ISSUE THREAD

**Issue by mwtoews** [pypa/setuptools#3735]
### setuptools version

65.6.3

### Python version

Python 3.11

### OS

linux

### Additional environment information

Run within an isolated build via `python -m build`

### Description

This is an issue for a project that uses pyproject.toml to define metadata using the dynamic readme feature provided by setuptools.

The contents of `pyproject.toml` contain these excerpts:
```toml
[build-system]
requires = ["setuptools >=61"]
build-backend = "setuptools.build_meta"

[project]
# ...
dynamic = ["readme"]

[tool.setuptools.dynamic]
readme = {file = ["docs/release.md", "LICENSE.md"]}
```

With the rendered METADATA file, "Description-Content-Type: text/x-rst" is found, which is incorrect. The concatenated description files are normal, but remain as Markdown format. This inconsistency of content-type is not detected by (e.g.) `twine check --strict dist/*`.

This is not an issue with declarative configurations with (e.g.) setup.cfg, which allows a field to explicitly state the content-type of the concatenated content:
```
[metadata]
# ...
long_description = file: docs/release.md, LICENSE.md
long_description_content_type = text/markdown
```

### Expected behavior

The content-type of the files should be auto-detected, and rendered as "Description-Content-Type: text/markdown". Inconsistencies or ambiguous guesses should raise warnings.

### How to Reproduce

1. create a demo project with the pyproject.toml content, and two Markdown files with `*.md` suffix
2. run `python -m build --wheel` to build the wheel and generate METADATA

### Output

METADATA contains "Description-Content-Type: text/x-rst"
