### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by whitequark** [pypa/setuptools#3807]
### setuptools version

setuptools===67.1.0

### Python version

Python 3.9.2

### OS

Debian 11

### Description

Setuptools validation for `pyproject.toml` dependency specifications is too strict and rejects `amaranth-yosys>=0.10.*`.

This doesn't match the grammar [defined in PEP 508](https://peps.python.org/pep-0508/#grammar).

You might ask yourself, "isn't this version specification the same as `amaranth-yosys>=0.10`?" The answer is no, try running both:
 - `pip install 'amaranth-yosys>=0.10.*'`
 - `pip install 'amaranth-yosys>=0.10'`

and comparing the result. Only the former will succeed since all of the `amaranth-yosys` distributions have a `.dev` suffix.

### Expected behavior

Setuptools accepts `amaranth-yosys>=0.10.*` in a dependency specification.

### How to Reproduce

Put the following in a `pyproject.toml` file in an empty directory:

```toml
[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "test-project"
version = "1.0"
dependencies = ["amaranth-yosys>=0.10.*"]
```

Install it with `pip install .`

### Output

```console
  configuration error: `project.dependencies[{data__dependencies_x}]` must be pep508
  DESCRIPTION:
      Project dependency specification according to PEP 508
  
  GIVEN VALUE:
      "amaranth-yosys>=0.10.*"
  
  OFFENDING RULE: 'format'
  
  DEFINITION:
      {
          "$id": "#/definitions/dependency",
          "title": "Dependency",
          "type": "string",
          "format": "pep508"
      }
```
