### ISSUE TITLE
[FR] Accept dynamic description to come from an attribute.

### ISSUE THREAD

**Issue by Lattay** [pypa/setuptools#3848]
### What's the problem this feature will solve?

It would make it possible to keep the package description in sync with the package docstring.

### Describe the solution you'd like

I propose to accept the following directives:

setup.cfg
```
description = attr: mypackage.__doc__
```

pyproject.toml
```
[tool.setuptools.dynamic]
description = {attr = "mypackage.__doc__"}
```

### Alternative Solutions

The current option is either to rely on setup.py or to manually keep the `__doc__` and description in sync which is prone to error.

### Additional context

I think this feature would be fairly easy to implement, as it is mostly a copy-paste from `version`. I tried to implement it myself, but I did not find what to do with the generated `_validate_pyproject` code.

Moreover, this feature is found in [flit](https://flit.pypa.io/en/stable/pyproject_toml.html#new-style-metadata).

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jb2170** [comment]
Bumping for this!

```toml
[project]
name = "MyLibrary"
dynamic = ["description", "version"]

[tool.setuptools.dynamic]
description = {attr = "MyLibrary.__doc__"}
version = {attr = "MyLibrary.__version__"}
```
