### ISSUE TITLE
[BUG] `pip install .` creates infinite nested `build/lib/build/lib/...`

### ISSUE THREAD

**Issue by casperdcl** [pypa/setuptools#4076]
- setuptools==68.2.2
- python==3.11.3
- OS: WSL2/debian & Windows
- pip==23.2.1

### Description

Cloning any PEP 517 (`pyproject.toml` not "legacy" `setup.py`) project and running `pip install .` will create a `build/lib` directory.

Subsequent `pip install .` will create more nested `build/lib` directories.

Eventually you will hit the OS path limit and get write errors, causing `pip install .` to fail.

### Expected behaviour

No infinite nested directories!

### How to Reproduce

```sh
mkdir -p pip-bug/test && cd pip-bug
touch test/__init__.py
cat <<EOF > pyproject.toml
```
```toml
[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
exclude = ["build"]

[project]
name = "test"
version = "0.0.0"
authors = [{name = "Casper da Costa-Luis", email = "casper.dcl@physics.org"}]
description = "PoC: repeated `pip install .` creates infinite nested build/lib/build/lib/..."
```
```sh
EOF
pip install . && pip install . && pip install .
tree
```

### Output

```console
.
├── build
│   ├── bdist.linux-x86_64
│   └── lib
│       ├── build
│       │   └── lib
│       │       ├── build
│       │       │   └── lib
│       │       │       └── test
│       │       │           └── __init__.py
│       │       └── test
│       │           └── __init__.py
│       └── test
│           └── __init__.py
├── pyproject.toml
├── test
│   └── __init__.py
└── test.egg-info
    ├── dependency_links.txt
    ├── PKG-INFO
    ├── SOURCES.txt
    └── top_level.txt

12 directories, 9 files
```

**Comment by abravalheri** [comment]
That happens because of explicitly adding `exclude = ["build"]`, but not `exclude = ["build*"]`.

Using `[tool.setuptools.packages.find] exclude = ["build"]` is equivalent to `setup.find_namespace_packages(exclude=["build"])`. This means that `build` is not listed in the output, but any of its subpackage is (see https://github.com/pypa/setuptools/issues/808 for the rationale of including subpackages even if the parent is not included)...

This is [documented](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages) as follows:

> **IMPORTANT**:
include and exclude accept strings representing [glob](https://docs.python.org/3/library/glob.html#module-glob) patterns. These patterns should match the full name of the Python module (as if it was written in an import statement).
>
> For example if you have util pattern, it will match util/__init__.py but not util/files/__init__.py.
> 
> The fact that the parent package is matched by the pattern will not dictate if the submodule will be included or excluded from the distribution. You will need to explicitly add a wildcard (e.g. util*) if you want the pattern to also match submodules.


If you remove `[tool.setuptools.packages.find]` the default behaviour is to ignore `build` and `build.*`... Alternatively you can also write `[tool.setuptools.packages.find] exclude = ["build*"]`, or simply use `include = ["<packagename>*"]`.

**Comment by casperdcl** [comment]
just for clarification:

all of this causes infinite `build/lib` recursion:

```toml
[tool.setuptools.packages.find]
exclude = ["foo", "bar"]
```
```toml
[tool.setuptools.packages.find]
exclude = ["foo", "bar", "build"]
```
```toml
[tool.setuptools.packages.find]
```

but these works fine:
```toml
[tool.setuptools.packages.find]
exclude = ["foo", "bar", "build*"]
```
```toml
[tool.setuptools.packages.find]
include = ["test"]
```

Seems like this should be really clearly documented in the docs for `exclude` ("if you use `exclude` you almost definitely need to explicitly add `"build*"`")

**Comment by casperdcl** [comment]
also btw

```toml
[tool.setuptools.packages.find]
include = ["test"]
```

seems to include both `test/__init__.py` as well as `test/sub/__init__.py` despite not having a wildcard
