### ISSUE TITLE
[FR] Extend the default tests glob inclusion

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#4460]
### What's the problem this feature will solve?

The docs @ https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html#controlling-files-in-the-distribution say:
> * Files that match the following glob patterns: `tests/test*.py`, `test/test*.py`;

Test files that have `_test` suffix in their base name are not included automatically. This is one of the common naming conventions. They should.

### Describe the solution you'd like

Including test files that have `_test` suffix in base name would be super useful. Additionally, does this recognize well-known names like `conftest.py`?

### Additional context

The example is a `pyproject.toml` looking as follows:
```toml
[build-system]
requires = [
  "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "lokiverse"
version = "1.0.0"
dependencies = [
  "cheroot",
]
```

The project has an `src/` layout with top-level `tests/` and the file at `tests/api_test.py` is not included.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct
