### ISSUE TITLE
[Docs] Missing recommendation on an upper bound version pin for build backends

### ISSUE THREAD

**Issue by leorochael** [pypa/setuptools#4521]
### Summary

Related to #4519 and #4520, but independent of them, there seems to be, at the very least, an important documentation bug:

Both on [Configuring setuptools using `pyproject.toml` files](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) and on [Building and Distributing Packages with Setuptools: `setup.cfg`-only projects](https://setuptools.pypa.io/en/latest/setuptools.html#setup-cfg-only-projects), the Setuptools documentation instructs developers to request the Setuptools build backend without an upper bound version pin, e.g:

```toml
[build-system]
requires = [
  "setuptools >= 40.9.0",
]
build-backend = "setuptools.build_meta"
```

```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
```

However this is not the first or the second time that a package fails to build with newer versions of setuptools that used to work with previous versions.

Pip's documentation has a slightly safer recommendation on [Build Process: Build time dependencies](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-time-dependencies):

```toml
[build-system]
requires = ["setuptools ~= 58.0", "cython ~= 0.29.0"]
```

(please ignore the `cython` pin, it's just for illustration purposes).

Considering the automatic behavior on build isolation to install the latest setuptools allowed by a package's build backend, and of Setuptools upgrade breaking builds based on earlier Setuptools releases, then Setuptools documentation should explicitly document adding an upper bound version pin for Setuptools.

Note that this is not a complaint on the fact that this kind of breakage can happen, as long as it happens between major versions, with an appropriately visible deprecation, but we should teach users of Setuptools how not to be unnecessarily exposed to it.

Notice that this will make it more likely that old packages might stop being installable if old versions of Setuptools itself become uninstallable by, say, newer versions of pip (as has happened), but I believe that older versions of setuptools becoming uninstallable happens more rarely than newer versions of Setuptools breaking older packages.

### OS / Environment

all

### Additional Information

When the documentation is improved, packages will hopefully start declaring an upper bound for versions of setuptools as a build-backend, which means build isolation by frontends (like pip or uv) will not install an incompatible version of setuptools for building a setuptools-build-backed package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct
