### ISSUE TITLE
[FR] Support dynamic attribute for description in pyproject.toml (as for `verison`)

### ISSUE THREAD

**Issue by Guts** [pypa/setuptools#4633]
### What's the problem this feature will solve?

Several of my projects are affected by https://github.com/pypa/pip/issues/11457, so I've undertaken a migration from setup.py to pyproject.toml. Initially, I planned to do this when Python 3.11 was the oldest supported version, as it was the first to integrate the toml lib as standard. But that's not the point.

Until now, I'd followed the former pypa packaging guide, which at the time mentioned the possibility of storing a package's metadata in a __about__.py file (or similar) so that it could be easily accessed from the rest of the package, setup.py but also the doc generation tools (typically Sphinx's conf.py), and so on.

When migrating, I saw that the description attribute was dynamic but only supported storage in a text file. This means that the description has to be duplicated or cannot be accessed easily from other tools/packages.

### Describe the solution you'd like

Based on [documentation](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata), I think it would be handy to write this:

```toml
[project]
name = "my_package"
dynamic = ["description", "version", "readme"]
# ...
[tool.setuptools.dynamic]
description= {attr = "my_package.__about__.__description__"}  # any module attribute compatible with ast.literal_eval
version = {attr = "my_package.__version__"}  # any module attribute compatible with ast.literal_eval
readme = {file = ["README.rst", "USAGE.rst"]}
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct
