### ISSUE TITLE
[BUG] editable installation - problem to find package members 

### ISSUE THREAD

**Issue by vanheck** [pypa/setuptools#4668]
### setuptools version

75.1.0

### Python version

3.12.7

### OS

debian boookworm

### Additional environment information

Project structure:
```
.
├── call_foo.py
├── Dockerfile
└── foo
    ├── foo
    │   ├── bar.py
    │   └── __init__.py
    └── pyproject.toml
```

`call_foo.py`:
```py
from importlib.metadata import version
print("setuptools:", version("setuptools"))
from foo import A
print(A())
```

`./Dockerfile`:
```Dockerfile
FROM python:3.12-slim-bookworm
WORKDIR /app
RUN pip install -U setuptools
COPY foo foo
RUN cd foo && pip install -e . && cd ..
COPY call_foo.py .
CMD [ "python", "call_foo.py" ]
```

`./foo/foo/bar.py`:
```py
class A: pass
```

`./foo/foo/__init__.py`:
```py
from foo.bar import A
__all__ = ["A"]  # same behavior whether this line is there or not
```

`./foo/pyproject.toml`:
```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "foo"
version = "0.1.0"
authors = [{ name = "me", email = "me@me.com" }]
description = "foo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ ]
[tool.setuptools.packages]
find = {}
```

### Description

If I use `pip install .` works well, but `pip install -e .` doesn't:

```py
from foo import A
```

### Expected behavior

Import should be passed.

### How to Reproduce

```sh
docker build -t foo .
docker run --rm -it foo
```

### Output

```py
setuptools: 75.1.0
Traceback (most recent call last):
  File "/app/call_foo.py", line 5, in <module>
    from foo import A
ImportError: cannot import name 'A' from 'foo' (unknown location)
```
