### ISSUE TITLE
[FR] Environment variables substitution for dynamic dependencies

### ISSUE THREAD

**Issue by sondalex** [pypa/setuptools#4765]
### What's the problem this feature will solve?

Setuptools supports dynamically specifying dependencies through `pyproject.toml` using the following syntax:

```toml
[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
```

The `requirements.txt` format, as described in the [pip documentation](https://pip.pypa.io/en/stable/reference/requirements-file-format/#using-environment-variables), includes a proposal for environment variable substitution. However, this functionality is not currently implemented in setuptools.

### Describe the solution you'd like

Introduce support in setuptools for substituting environment variables when parsing dependencies from a `requirements.txt` file. This would enable use cases like the following:

1. **Define a private dependency in `requirements.txt`:**

   ```text
   mypackage@https://${PAT}@<pypi-feed>/<path>
   ```

2. **Specify dynamic dependencies in `pyproject.toml`:**

   ```toml
   [project]
   # Other project metadata
   dynamic = ["dependencies"]

   [tool.setuptools.dynamic]
   dependencies = { file = ["requirements.txt"] }
   ```

3. **Set the necessary environment variables before installation:**

   ```bash
   export PAT=...
   export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring # To avoid interactive prompts
   ```

4. **Run the installation:**

   ```bash
   pip install .
   ```

This feature would be especially beneficial for non-interactive sessions, such as CI/CD pipelines.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct
